---
resource_types:
- name: serverless
  type: docker-image
  source:
    repository: sjback/concourse-serverless
    tag: latest

resources:
- name: example-repo
  type: git
  source:
    uri: git@github.com:hexlyops/serverless-example.git
    private_key: ((github-key))
    branch: master

- name: deploy
  type: serverless
  source:
    access_key_id: ((aws.key))
    secret_access_key: ((aws.secret))
    region_name: us-east-1

jobs:
  - name: deploy-hello-world
    plan:
      - get: example-repo

      - put: deploy
        params:
          deploy: true
          npm_install: true
          npm_build: true
          npm_prefix: example-repo
          stage: dev
          serverless: example-repo/serverless

